### ISSUE TITLE
Why another one?

### ISSUE THREAD

**Issue by Ciao121** [davidepedrazzi/ipify2#1]
Hi,
What's the difference between this and https://github.com/sindresorhus/ipify ?

**Comment by davidepedrazzi** [comment]
Hello, @Ciao121,

ipify2 relies on https://github.com/axios/axios instead of https://github.com/sindresorhus/got implementing both IPv4 and IPv6 while ipify is limited to IPv4. In my opinion ipify2 is also cleaner, allowing a more flexible usage than ipify but this is subjective.

Thank you for your interest,

Davide Pedrazzi.
